name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
        GOOGLE_APPLICATION_CREDENTIALS: best-trucks-d91b7b438b2e.json

    steps:
      - uses: actions/checkout@v2
        
      - uses: actions/setup-python@v2
        with:
            python-version: '3.8'

      - name: Install dependencies
        run: |
            pip install --upgrade pip wheel pytest
            pip install -r requirements.txt

      - name: Run tests
        run: pytest
